# A message containing various forces on the car

# Car tyre forces
float64 front_left_lateral
float64 front_left_longitudinal
float64 front_left_vertical

float64 front_right_lateral
float64 front_right_longitudinal
float64 front_right_vertical

float64 rear_left_lateral
float64 rear_left_longitudinal
float64 rear_left_vertical

float64 rear_right_lateral
float64 rear_right_longitudinal
float64 rear_right_vertical